### ISSUE TITLE
40 Second Startup Times

### ISSUE THREAD

**Issue by PythonLinks** [Xh4H/Discord.jl#25]
If you've run into a bug, please supply the following information:

* Julia and platform version information (with `versioninfo()`)
versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7601 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)

* Package version information (with `]status`)
[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Discord = "fcbf000d-02fd-53f1-af91-d952191673d3"

HERE IS MY FILE
`
using Discord

function on_message_ready(client::Client, event::Discord.Ready)
    println("You are Connected to the server. ")
end
client = Client("DISCORD TOKEN GOES HERE")
open(client)    
add_handler!(client, Ready, on_message_ready; tag=:ready)
wait(client)
`

**Comment by PythonLinks** [comment]
My suspicion is that these huge delays in start up are related to a networking problem. 
If you take a look at the gateway code
https://github.com/Xh4H/Discord.jl/blob/master/src/gateway/gateway.jl
It mentions 5 second delays and 7 second delays. 

So, for fun, I think I am going to dig into that.  I will start by Logging if that is really where the delays are.  
Maybe it is fixable. 

I just saw the Julia con video on "The Unreasonable Effectiveness of Multiple Dispatch. "
https://www.youtube.com/watch?v=kc9HwsxE1OY

They need another one on  "The unreasonable ease of debugging Cooperating Sequential Processes"

So I really want to start using Julia.   But the 40 second delay needs to be vanquished. 

Oh, I see.  Only 4 people are watching this repository.  3 not counting me.

**Comment by christopher-dG** [comment]
Julia is jit-compiled, the slow startup is due to loads of code being compiled.

**Comment by christopher-dG** [comment]
You can look into [PackageCompiler](https://github.com/JuliaLang/PackageCompiler.jl) to help get rid of it.

**Comment by Xh4H** [comment]
I'm closing this issue. It has been commented many times in the past, as well as how to fix it.
